### ISSUE TITLE
Thanks for using rdkit-js!

### ISSUE THREAD

**Issue by MichelML** [swamidass/xenosite#1]
Hi, thanks for trying rdkit-js, I was wondering if you had any feedback on its usage?

- Were some features missing?
- How could its usage be improved?
- Anything else you would like to see in rdkit-js?

I wish you success with this project :pray:

**Comment by MichelML** [comment]
Feel free to add your feedback directly on this page, and close this issue whenever you feel like it!

https://github.com/rdkit/rdkit-js/discussions/150

**Comment by swamidass** [comment]
Thanks for the note, and thanks for developing rdkit. 

The biggest challenge we've had is in extracting the SVG coordinates output from rdkit. As it is, I am not sure if it's possible to do so.  We need that to be able to shade molecules by ML predictions. See here, for example, what we are trying to do, and are able to do with the c++ version quite easily: https://xenopict.readthedocs.io/en/latest/quickstart.html.

Would you be willing to add the right interface so that we can do the same in javascript? That would be really nice if that is possible.
